"""baseline schema

Revision ID: 45984fddfba7
Revises: 
Create Date: 2026-07-22 23:20:14.191302

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45984fddfba7'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('background_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(length=80), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'completed', 'failed', name='job_status'), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_background_jobs_available_at'), 'background_jobs', ['available_at'], unique=False)
    op.create_index(op.f('ix_background_jobs_id'), 'background_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_background_jobs_job_type'), 'background_jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_background_jobs_status'), 'background_jobs', ['status'], unique=False)
    op.create_table('portal_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'student', name='user_role'), nullable=False),
    sa.Column('auth_provider', sa.Enum('password', 'google', name='auth_provider'), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('reset_token_hash', sa.String(length=255), nullable=True),
    sa.Column('reset_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portal_users_email'), 'portal_users', ['email'], unique=True)
    op.create_index(op.f('ix_portal_users_id'), 'portal_users', ['id'], unique=False)
    op.create_index(op.f('ix_portal_users_username'), 'portal_users', ['username'], unique=True)
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_username', sa.String(length=80), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['portal_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_actor_id'), 'audit_events', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_id'), 'audit_events', ['id'], unique=False)
    op.create_table('portal_exams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('block_clipboard', sa.Boolean(), nullable=False),
    sa.Column('block_context_menu', sa.Boolean(), nullable=False),
    sa.Column('block_inspect_shortcuts', sa.Boolean(), nullable=False),
    sa.Column('enforce_fullscreen', sa.Boolean(), nullable=False),
    sa.Column('track_focus_loss', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['portal_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portal_exams_id'), 'portal_exams', ['id'], unique=False)
    op.create_table('exam_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['portal_exams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['portal_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_assignments_exam_id'), 'exam_assignments', ['exam_id'], unique=False)
    op.create_index(op.f('ix_exam_assignments_id'), 'exam_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_exam_assignments_student_id'), 'exam_assignments', ['student_id'], unique=False)
    op.create_table('exam_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('option_a', sa.String(length=255), nullable=False),
    sa.Column('option_b', sa.String(length=255), nullable=False),
    sa.Column('option_c', sa.String(length=255), nullable=False),
    sa.Column('option_d', sa.String(length=255), nullable=False),
    sa.Column('correct_option', sa.String(length=1), nullable=False),
    sa.Column('marks', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['portal_exams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_questions_exam_id'), 'exam_questions', ['exam_id'], unique=False)
    op.create_index(op.f('ix_exam_questions_id'), 'exam_questions', ['id'], unique=False)
    op.create_table('exam_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('in_progress', 'submitted', name='attempt_status'), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('total_marks', sa.Integer(), nullable=False),
    sa.Column('percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['exam_assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['portal_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_attempts_assignment_id'), 'exam_attempts', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_exam_attempts_id'), 'exam_attempts', ['id'], unique=False)
    op.create_index(op.f('ix_exam_attempts_student_id'), 'exam_attempts', ['student_id'], unique=False)
    op.create_table('attempt_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('selected_option', sa.String(length=1), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('marks_awarded', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['exam_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['exam_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attempt_answers_attempt_id'), 'attempt_answers', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_attempt_answers_id'), 'attempt_answers', ['id'], unique=False)
    op.create_index(op.f('ix_attempt_answers_question_id'), 'attempt_answers', ['question_id'], unique=False)
    op.create_table('security_incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('incident_type', sa.String(length=80), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['exam_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exam_id'], ['portal_exams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['portal_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_incidents_attempt_id'), 'security_incidents', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_security_incidents_exam_id'), 'security_incidents', ['exam_id'], unique=False)
    op.create_index(op.f('ix_security_incidents_id'), 'security_incidents', ['id'], unique=False)
    op.create_index(op.f('ix_security_incidents_student_id'), 'security_incidents', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_security_incidents_student_id'), table_name='security_incidents')
    op.drop_index(op.f('ix_security_incidents_id'), table_name='security_incidents')
    op.drop_index(op.f('ix_security_incidents_exam_id'), table_name='security_incidents')
    op.drop_index(op.f('ix_security_incidents_attempt_id'), table_name='security_incidents')
    op.drop_table('security_incidents')
    op.drop_index(op.f('ix_attempt_answers_question_id'), table_name='attempt_answers')
    op.drop_index(op.f('ix_attempt_answers_id'), table_name='attempt_answers')
    op.drop_index(op.f('ix_attempt_answers_attempt_id'), table_name='attempt_answers')
    op.drop_table('attempt_answers')
    op.drop_index(op.f('ix_exam_attempts_student_id'), table_name='exam_attempts')
    op.drop_index(op.f('ix_exam_attempts_id'), table_name='exam_attempts')
    op.drop_index(op.f('ix_exam_attempts_assignment_id'), table_name='exam_attempts')
    op.drop_table('exam_attempts')
    op.drop_index(op.f('ix_exam_questions_id'), table_name='exam_questions')
    op.drop_index(op.f('ix_exam_questions_exam_id'), table_name='exam_questions')
    op.drop_table('exam_questions')
    op.drop_index(op.f('ix_exam_assignments_student_id'), table_name='exam_assignments')
    op.drop_index(op.f('ix_exam_assignments_id'), table_name='exam_assignments')
    op.drop_index(op.f('ix_exam_assignments_exam_id'), table_name='exam_assignments')
    op.drop_table('exam_assignments')
    op.drop_index(op.f('ix_portal_exams_id'), table_name='portal_exams')
    op.drop_table('portal_exams')
    op.drop_index(op.f('ix_audit_events_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_portal_users_username'), table_name='portal_users')
    op.drop_index(op.f('ix_portal_users_id'), table_name='portal_users')
    op.drop_index(op.f('ix_portal_users_email'), table_name='portal_users')
    op.drop_table('portal_users')
    op.drop_index(op.f('ix_background_jobs_status'), table_name='background_jobs')
    op.drop_index(op.f('ix_background_jobs_job_type'), table_name='background_jobs')
    op.drop_index(op.f('ix_background_jobs_id'), table_name='background_jobs')
    op.drop_index(op.f('ix_background_jobs_available_at'), table_name='background_jobs')
    op.drop_table('background_jobs')
    # ### end Alembic commands ###
